### ISSUE TITLE
Problem installing integron_finder via bioconda

### ISSUE THREAD

**Issue by evolarjun** [gem-pasteur/Integron_Finder#82]
Problem installing integron_finder via bioconda:

## Version of Integron_Finder:

Write here the output of integron_finder --version.
No output. 
### OS

- [X] Linux
- [ ] Windows
- [ ] Mac

## Expected behavior

Get version. Note:
```
$ conda info integron_finder

integron_finder 2.0rc6 py_0
---------------------------
file name   : integron_finder-2.0rc6-py_0.tar.bz2
name        : integron_finder
version     : 2.0rc6
build string: py_0
build number: 0
channel     : https://conda.anaconda.org/bioconda/noarch
size        : 30.9 MB
arch        : None
constrains  : ()
license     : GPLv3
md5         : a3bd84a58158006f9ff95489f26326ba
noarch      : python
package_type: noarch_python
platform    : None
sha256      : 4605b4908a3691b9f8b1398cf5ae388ab5fa24bdfc3d7cef45bf1d130705fa9a
subdir      : noarch
timestamp   : 1594049184104
url         : https://conda.anaconda.org/bioconda/noarch/integron_finder-2.0rc6-py_0.tar.bz2
dependencies:
    biopython >=1.70
    colorlog
    hmmer >=3.1
    infernal >=1.1.2
    matplotlib-base
    numpy >=1.14.2
    pandas >=0.22.0
    prodigal >=2.6.2
    python >=3.4
WARNING: 'conda info package_name' is deprecated.
          Use 'conda search package_name --info'.
```

## Actual behavior

```
$ conda create -y -n integron_finder
...
$ conda activate integron_finder
$ conda install -y integron_finder
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/aprasad/miniconda3/envs/integron_finder

  added / updated specs:
    - integron_finder


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_gnu
  biopython          conda-forge/linux-64::biopython-1.78-py39h3811e60_2
  ca-certificates    conda-forge/linux-64::ca-certificates-2020.12.5-ha878542_0
  certifi            conda-forge/linux-64::certifi-2020.12.5-py39hf3d152e_1
  colorlog           conda-forge/linux-64::colorlog-4.8.0-py39hf3d152e_0
  cycler             conda-forge/noarch::cycler-0.10.0-py_2
  freetype           conda-forge/linux-64::freetype-2.10.4-h0708190_1
  hmmer              bioconda/linux-64::hmmer-3.3.2-h1b792b2_1
  infernal           bioconda/linux-64::infernal-1.1.4-h779adbc_0
  integron_finder    bioconda/noarch::integron_finder-2.0rc6-py_0
  jpeg               conda-forge/linux-64::jpeg-9d-h36c2ea0_0
  kiwisolver         conda-forge/linux-64::kiwisolver-1.3.1-py39h1a9c180_1
  lcms2              conda-forge/linux-64::lcms2-2.12-hddcbb42_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.35.1-hea4e1c9_2
  libblas            conda-forge/linux-64::libblas-3.9.0-8_openblas
  libcblas           conda-forge/linux-64::libcblas-3.9.0-8_openblas
  libffi             conda-forge/linux-64::libffi-3.3-h58526e2_2
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.3.0-h2828fa1_18
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-9.3.0-hff62375_18
  libgfortran5       conda-forge/linux-64::libgfortran5-9.3.0-hff62375_18
  libgomp            conda-forge/linux-64::libgomp-9.3.0-h2828fa1_18
  liblapack          conda-forge/linux-64::liblapack-3.9.0-8_openblas
  libopenblas        conda-forge/linux-64::libopenblas-0.3.12-pthreads_h4812303_1
  libpng             conda-forge/linux-64::libpng-1.6.37-h21135ba_2
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.3.0-h6de172a_18
  libtiff            conda-forge/linux-64::libtiff-4.2.0-hdc55705_0
  libwebp-base       conda-forge/linux-64::libwebp-base-1.2.0-h7f98852_2
  lz4-c              conda-forge/linux-64::lz4-c-1.9.3-h9c3ff4c_0
  matplotlib-base    conda-forge/linux-64::matplotlib-base-3.4.1-py39h2fa2bec_0
  ncurses            conda-forge/linux-64::ncurses-6.2-h58526e2_4
  numpy              conda-forge/linux-64::numpy-1.20.2-py39hdbf815f_0
  olefile            conda-forge/noarch::olefile-0.46-pyh9f0ad1d_1
  openssl            conda-forge/linux-64::openssl-1.1.1k-h7f98852_0
  pandas             conda-forge/linux-64::pandas-1.2.3-py39hde0f152_0
  pillow             conda-forge/linux-64::pillow-8.1.2-py39hf95b381_0
  pip                conda-forge/noarch::pip-21.0.1-pyhd8ed1ab_0
  prodigal           bioconda/linux-64::prodigal-2.6.3-h779adbc_3
  pyparsing          conda-forge/noarch::pyparsing-2.4.7-pyh9f0ad1d_0
  python             conda-forge/linux-64::python-3.9.2-hffdb5ce_0_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  python_abi         conda-forge/linux-64::python_abi-3.9-1_cp39
  pytz               conda-forge/noarch::pytz-2021.1-pyhd8ed1ab_0
  readline           conda-forge/linux-64::readline-8.0-he28a2e2_2
  setuptools         conda-forge/linux-64::setuptools-49.6.0-py39hf3d152e_3
  six                conda-forge/noarch::six-1.15.0-pyh9f0ad1d_0
  sqlite             conda-forge/linux-64::sqlite-3.35.4-h74cdb3f_0
  tk                 conda-forge/linux-64::tk-8.6.10-h21135ba_1
  tornado            conda-forge/linux-64::tornado-6.1-py39h3811e60_1
  tzdata             conda-forge/noarch::tzdata-2021a-he74cb21_0
  wheel              conda-forge/noarch::wheel-0.36.2-pyhd3deb0d_0
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_1
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1010
  zstd               conda-forge/linux-64::zstd-1.4.9-ha95c52a_0


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
$ integron_finder --version
Traceback (most recent call last):
  File "/home/aprasad/miniconda3/envs/integron_finder/bin/integron_finder", line 7, in <module>
    from integron_finder.scripts.finder import main
  File "/home/aprasad/miniconda3/envs/integron_finder/lib/python3.9/site-packages/integron_finder/scripts/finder.py", line 51, in <module>
    from integron_finder import utils
  File "/home/aprasad/miniconda3/envs/integron_finder/lib/python3.9/site-packages/integron_finder/utils.py", line 62, in <module>
    read_multi_prot_fasta = make_multi_fasta_reader(Seq.IUPAC.extended_protein)
AttributeError: module 'Bio.Seq' has no attribute 'IUPAC'
```
## Steps to reproduce behavior

See above

## Relevant logs and/or screenshots

(Paste any relevant logs - please use code blocks (```) to format console output,
logs, and code as it's very hard to read otherwise.)

**Comment by jeanrjc** [comment]
You can try to install like this instead : 

```bash
conda create --name IFv2 python=3.6 
conda config --add channels bioconda # if it's not already the case
conda activate IFv2    
conda install integron_finder # install integron_finder
conda install biopython==1.72 # downgrade biopython and pandas waiting for upcoming fixes
conda install pandas=0.25.3
integron_finder ...
conda deactivate
```

@bneron wasn't it fix ?

**Comment by evolarjun** [comment]
I gave up on conda and the release version, and was able to get the master branch on git working using the following on an Ubuntu 20.04 box. My end goal was an installation for multiple users, so this worked well:
 
```
# prerequisites
# hmmer
sudo apt-get install hmmer
# prodigal
mkdir prodigal
cd prodigal
wget https://github.com/hyattpd/Prodigal/releases/download/v2.6.3/prodigal.linux
chmod 755 prodigal.linux
sudo mv prodigal.linux /usr/local/bin/prodigal
cd ..
rmdir prodigal
# nextflow
 # (requires Java)
sudo apt-get install default-jre
java --version
# nextflow
curl -s https://get.nextflow.io | bash
sudo mv nextflow /usr/local/bin
sudo chmod a+r /usr/local/bin/nextflow

# now install integron_finder
sudo apt-get install python3-pip
git clone https://github.com/gem-pasteur/Integron_Finder.git
cd Integron_Finder
sudo python3 -m pip install --system -e .
```

I will try the conda instructions you posted above and report back.

**Comment by evolarjun** [comment]
I just tried the bioconda instructions above and they appear to work too.

Thanks!

**Comment by joshamilton** [comment]
As of September 23, 2021, the colorlog package also needs to be downgraded to prevent the error message:

> Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/integron_finder/bin/integron_finder", line 10, in <module>
    sys.exit(main())
  File "/home/ec2-user/anaconda3/envs/integron_finder/lib/python3.6/site-packages/integron_finder/scripts/finder.py", line 513, in main
    out=not config.mute)
  File "/home/ec2-user/anaconda3/envs/integron_finder/lib/python3.6/site-packages/integron_finder/__init__.py", line 78, in init_logger
    logging = colorlog.logging.logging
AttributeError: module 'colorlog' has no attribute 'logging'

Downgrading to 4.8.0 allows integron_finder to run. I did not try intermediate versions between 4.8.0 and the current 6.4.1.

**Comment by bneron** [comment]
or use the master version of Integron_Finder
