### ISSUE TITLE
fillna="na" error if pandas version 0.19.0, solved by downgrading pandas to 0.18.0

### ISSUE THREAD

**Issue by SwapnilDoijad** [gem-pasteur/Integron_Finder#18]
After upgrading pandas to 0.19.0 following error occurred

---

In replicon ABC-1, there are:
- 1 complete integron(s) found with a total 2 attC site(s)
- 0 CALIN element(s) found with a total of 0 attC site(s)
- 0 In0 element(s) found with a total of 0 attC site
  Traceback (most recent call last):
  File "/usr/local/bin/integron_finder", line 1746, in <module>
    integrons_describe.to_csv(os.path.join(out_dir_ok, outfile), sep="\t", index=0, fillna="na")
  TypeError: to_csv() got an unexpected keyword argument 'fillna'

---

Currently, the error got resolved by downgrading pandas to 0.18.0

Any other option to get Integron_Finder work with upgraded pandas?

**Comment by jeanrjc** [comment]
This is going to be fixed in the next release. 
Meanwhile, you can use pandas 0.18.0 (as said by @SwapnilDoijad )

**Comment by jeanrjc** [comment]
Release 1.5.1 fix this issue.
